"""API Schema 模块

包含所有 API 请求和响应的 Pydantic 模型定义.
"""

# 生成命令: /speckit.implement T019
# 生成时间: 2025-12-09
# 来源: specs/001-multi-agent-doc-system/tasks.md

# 导入所有Schema模块
from .document_schemas import (
    BatchDocumentProcessRequest,
    BatchDocumentProcessResponse,
    ChartConversionResult,
    CleaningLevel,
    DocumentDeleteRequest,
    DocumentDeleteResponse,
    DocumentFormat,
    DocumentListResponse,
    DocumentMetadata,
    DocumentProcessingDetail,
    DocumentProcessRequest,
    DocumentProcessResponse,
    DocumentQueryRequest,
    DocumentQueryRequestValidator,
    DocumentResponse,
    DocumentStatus,
    DocumentUploadRequest,
    DocumentUploadRequestValidator,
    DocumentUploadResponse,
    DocumentValidationResponse,
    ErrorResponse,
    FormatInfo,
    ProcessingProgressResponse,
    ProcessingStatistics,
    ProcessingStatus,
    create_error_response,
    create_success_response,
)
from .industry_selection_schemas import (
    DatabaseDetailRequest,
    DatabaseListResponse,
    DatabaseResponse,
    DeleteResponse,
    IndustryDatabaseListRequest,
    IndustryDetailRequest,
    IndustryListRequest,
    IndustryListResponse,
    IndustryResponse,
    IndustrySelectionDetailRequest,
    IndustrySelectionListRequest,
    IndustrySelectionListResponse,
    IndustrySelectionRequest,
    IndustrySelectionRequestValidator,
    IndustrySelectionResponse,
    IndustrySelectionUpdateRequest,
    IndustrySelectionUpdateRequestValidator,
    IndustryStatisticsRequest,
    IndustryStatisticsResponse,
    IndustryValidationRequest,
    IndustryValidationResponse,
    SortBy,
    SortOrder,
    SuccessResponse,
    create_database_response,
    create_error_response as industry_create_error_response,
    create_industry_response,
    create_success_response as industry_create_success_response,
)
from .knowledge_base_schemas import (
    ChunkingConfig,
    CreateKnowledgeBaseRequest,
    CreateKnowledgeBaseResponse,
    DeleteKnowledgeBaseResponse,
    DocumentLevel,
    ErrorResponse as KBErrorResponse,
    FusionStrategy,
    HybridRetrieverConfig,
    IndexStatistics,
    KnowledgeBaseConfig,
    KnowledgeBaseResponse,
    KnowledgeBaseStatus,
    KnowledgeBaseStatusResponse,
    QueryKnowledgeBaseRequest,
    QueryKnowledgeBaseResponse,
    QueryResult,
    QueryType,
    SortOrder as KBSortOrder,
    StructuredQueryRequest,
    UpdateKnowledgeBaseRequest,
    UpdateKnowledgeBaseResponse,
    create_error_response as kb_create_error_response,
    create_success_response as kb_create_success_response,
)

__all__ = [
    "BatchDocumentProcessRequest",
    "BatchDocumentProcessResponse",
    "ChartConversionResult",
    "ChunkingConfig",
    "CleaningLevel",
    "CreateKnowledgeBaseRequest",
    "CreateKnowledgeBaseResponse",
    "DatabaseDetailRequest",
    "DatabaseListResponse",
    "DatabaseResponse",
    "DeleteKnowledgeBaseResponse",
    "DeleteResponse",
    "DocumentDeleteRequest",
    "DocumentDeleteResponse",
    # Document Schemas
    "DocumentFormat",
    "DocumentLevel",
    "DocumentListResponse",
    "DocumentMetadata",
    "DocumentProcessRequest",
    "DocumentProcessResponse",
    "DocumentProcessingDetail",
    "DocumentQueryRequest",
    "DocumentQueryRequestValidator",
    "DocumentResponse",
    "DocumentStatus",
    "DocumentUploadRequest",
    "DocumentUploadRequestValidator",
    "DocumentUploadResponse",
    "DocumentValidationResponse",
    "ErrorResponse",
    "FormatInfo",
    "FusionStrategy",
    "HybridRetrieverConfig",
    "IndexStatistics",
    "IndustryDatabaseListRequest",
    "IndustryDetailRequest",
    "IndustryListRequest",
    "IndustryListResponse",
    "IndustryResponse",
    "IndustrySelectionDetailRequest",
    "IndustrySelectionListRequest",
    "IndustrySelectionListResponse",
    "IndustrySelectionRequest",
    "IndustrySelectionRequestValidator",
    "IndustrySelectionResponse",
    "IndustrySelectionUpdateRequest",
    "IndustrySelectionUpdateRequestValidator",
    "IndustryStatisticsRequest",
    "IndustryStatisticsResponse",
    "IndustryValidationRequest",
    "IndustryValidationResponse",
    "KBErrorResponse",
    "KBSortOrder",
    "KnowledgeBaseConfig",
    "KnowledgeBaseResponse",
    # Knowledge Base Schemas
    "KnowledgeBaseStatus",
    "KnowledgeBaseStatusResponse",
    "ProcessingProgressResponse",
    "ProcessingStatistics",
    "ProcessingStatus",
    "QueryKnowledgeBaseRequest",
    "QueryKnowledgeBaseResponse",
    "QueryResult",
    "QueryType",
    "SortBy",
    # Industry Selection Schemas
    "SortOrder",
    "StructuredQueryRequest",
    "SuccessResponse",
    "UpdateKnowledgeBaseRequest",
    "UpdateKnowledgeBaseResponse",
    "create_database_response",
    "create_error_response",
    "create_industry_response",
    "create_success_response",
    "industry_create_error_response",
    "industry_create_success_response",
    "kb_create_error_response",
    "kb_create_success_response",
]
